### ISSUE TITLE
Duplicates in list while sorting the columns

### ISSUE THREAD

**Issue by yashwanth-Thota** [sampath220/reduxwithhooks#3]
Duplicates are being added to the list while we are sorting the columns

**Comment by sampath220** [comment]
yaa,find it and do it

**Comment by yashwanth-Thota** [comment]
Did not get it .can you add some more info

**Comment by sampath220** [comment]
New row is inserting while sorting when we have duplicate cricketers

**Comment by yashwanth-Thota** [comment]
1.Initial
https://user-images.githubusercontent.com/37128171/75983026-bbe85300-5f0d-11ea-80e0-71cd3226365b.JPG)
2.Added duplicate MS Dhoni (https://user-images.githubusercontent.com/37128171/75983030-bd198000-5f0d-11ea-9449-7407fd1d755d.JPG)
3.Sorted and found duplicates being added (https://user-images.githubusercontent.com/37128171/75983033-bdb21680-5f0d-11ea-9798-634ee790238d.JPG)

**Comment by yashwanth-Thota** [comment]
Issues fixed added changes in commit(Fix- Duplicates issue while sorting)
